import { WMSLayerConfig, LayerPreset } from '../types';

export const OFFICIAL_WMS_LAYERS: WMSLayerConfig[] = [
  // =========================================================================
  // BLOQUE 1: EXCLUSIONES LEGALES Y AMBIENTALES (MODELO R1 / R2 - D.L. 1278)
  // =========================================================================
  {
    id: 'anp_definitivas',
    nombre: 'Áreas Naturales Protegidas Definitivas (SERNANP / SINANPE)',
    entidad: 'SERNANP',
    urlWms: '/CAPAS/ANP Nacional Definitivas.kmz',
    layers: 'ANP Nacional Definitivas.kmz',
    categoria: 'EXCLUSION_LEGAL',
    opacidad: 0.85,
    visible: true,
    descripcion: 'Zonas de Exclusión Absoluta D.L. 1278 (SERNANP SINANPE polígonos locales definitivos 3 MB).',
    preset: ['preset_minam', 'preset_exclusion']
  },
  {
    id: 'catastro_monumentos',
    nombre: 'Patrimonio Cultural y Sitios Arqueológicos CIRA (MINCUL)',
    entidad: 'MINCUL',
    urlWms: '/CAPAS/Catastro de Monumentos Arqueologico CIRA.kmz',
    layers: 'Catastro de Monumentos Arqueologico CIRA.kmz',
    categoria: 'EXCLUSION_LEGAL',
    opacidad: 0.85,
    visible: true,
    descripcion: 'Polígonos y puntos oficiales de Sitios y Zonas Arqueológicas declarados Patrimonio Cultural Inalienable (2.57 MB).',
    preset: ['preset_minam', 'preset_exclusion']
  },

  // --- GRUPO COLAPSABLE: FAJAS MARGINALES E HIDROGRAFÍA (ANA / SNIRH) ---
  {
    id: 'rios_lagos_ana',
    nombre: 'Fajas Marginales, Ríos y Lagos (ANA / SNIRH)',
    subNombre: 'Ríos, Quebradas y Fajas Marginales Principales',
    grupo: 'hidrografia',
    groupNombre: 'Fajas Marginales e Hidrografía (ANA / SNIRH)',
    entidad: 'ANA',
    urlWms: '/CAPAS/RIOS_QUEBARDAS_LAGOS.kmz',
    layers: 'RIOS_QUEBARDAS_LAGOS.kmz',
    categoria: 'EXCLUSION_LEGAL',
    opacidad: 0.85,
    visible: true,
    descripcion: 'Red hidrográfica nacional, ríos principales y fajas marginales inalienables (Ley 29338).',
    preset: ['preset_minam', 'preset_exclusion']
  },
  {
    id: 'lagos_lagunas',
    nombre: 'Lagos y Lagunas del Perú (IGN / ANA)',
    subNombre: 'Lagos y Lagunas Continentales (14.6 MB)',
    grupo: 'hidrografia',
    groupNombre: 'Fajas Marginales e Hidrografía (ANA / SNIRH)',
    entidad: 'ANA',
    urlWms: '/CAPAS/Lagos y Lagunas.kmz',
    layers: 'Lagos y Lagunas.kmz',
    categoria: 'EXCLUSION_LEGAL',
    opacidad: 0.85,
    visible: false,
    descripcion: 'Cuerpos de agua lénticos continentales y lagunas altoandinas del IGN / ANA.',
    preset: ['preset_exclusion']
  },
  {
    id: 'rios_lineal',
    nombre: 'Red Fluvial Lineal Nacional (ANA / SNIRH)',
    subNombre: 'Red Fluvial Continua Detallada (141 MB)',
    grupo: 'hidrografia',
    groupNombre: 'Fajas Marginales e Hidrografía (ANA / SNIRH)',
    entidad: 'ANA',
    urlWms: '/CAPAS/Rios Lineal.kmz',
    layers: 'Rios Lineal.kmz',
    categoria: 'EXCLUSION_LEGAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Red fluvial continua a nivel nacional con cauces principales y tributarios (Capa pesada: 141 MB).',
    preset: ['preset_exclusion']
  },
  {
    id: 'lago_titicaca',
    nombre: 'Lago Titicaca (Cuerpo Mayor)',
    subNombre: 'Lago Titicaca (Espejo Mayor)',
    grupo: 'hidrografia',
    groupNombre: 'Fajas Marginales e Hidrografía (ANA / SNIRH)',
    entidad: 'ANA',
    urlWms: '/CAPAS/Lago Titicaca.kmz',
    layers: 'Lago Titicaca.kmz',
    categoria: 'EXCLUSION_LEGAL',
    opacidad: 0.85,
    visible: false,
    descripcion: 'Polígono del espejo de agua del Lago Titicaca.',
    preset: ['preset_exclusion']
  },

  // --- ACUÍFEROS Y HUMEDALES ---
  {
    id: 'ecosistemas_fragiles',
    nombre: 'Ecosistemas Frágiles y Humedales (SERFOR / MINAM)',
    entidad: 'MINAM',
    urlWms: '/CAPAS/SERFOR_Ecosistemas_Fragiles.kmz',
    layers: 'SERFOR_Ecosistemas_Fragiles.kmz',
    categoria: 'EXCLUSION_LEGAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Lomas costeras, bofedales, albuferas y puquios catalogados en la Lista Nacional SERFOR (1.4 MB).',
    preset: ['preset_minam']
  },
  {
    id: 'mapa_hidrogeologico',
    nombre: 'Mapa Hidrogeológico y Acuíferos Vulnerables (INGEMMET)',
    entidad: 'INGEMMET',
    urlWms: '/CAPAS/INGEMMET_Mapa_Hidrogeologico_Peru.kmz',
    layers: 'INGEMMET_Mapa_Hidrogeologico_Peru.kmz',
    categoria: 'EXCLUSION_LEGAL',
    opacidad: 0.75,
    visible: false,
    descripcion: 'Vulnerabilidad hidrogeológica y napas freáticas según INGEMMET.',
    preset: ['preset_minam']
  },
  {
    id: 'zona_amortiguamiento',
    nombre: 'Zonas de Amortiguamiento ANP (SERNANP / GEOSERNANP)',
    entidad: 'SERNANP',
    urlWms: '/CAPAS/Zona_Amortiguamiento_SERNANP.kmz',
    layers: 'Zona_Amortiguamiento_SERNANP.kmz',
    categoria: 'EXCLUSION_LEGAL',
    opacidad: 0.75,
    visible: false,
    descripcion: 'Franjas de amortiguamiento adyacentes a ANP que requieren opinión técnica vinculante (5.7 MB).',
    preset: ['preset_minam']
  },

  // =========================================================================
  // BLOQUE 2: RESTRICCIONES TÉCNICAS (MODELO R3 - D.L. 1278 / GUÍA MINAM)
  // =========================================================================
  {
    id: 'catastro_urbano_buffer',
    nombre: 'Distancia a Centros Poblados y Casco Urbano (≥ 500 m)',
    entidad: 'COFOPRI',
    urlWms: '/CAPAS/catastro_urbano.kmz',
    layers: 'catastro_urbano.kmz',
    categoria: 'RESTRICCION_TECNICA',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Manzanas urbanas consolidadas y catastro formalizado para verificar buffer sanitario normativo de 500 m (D.L. 1278).',
    preset: ['preset_minam', 'preset_restriccion']
  },
  {
    id: 'radio_seguridad_aviaria',
    nombre: 'Radio Seguridad Aviaria Aeropuertos ≥ 13 km (MTC / DGAC)',
    entidad: 'MTC',
    urlWms: '/CAPAS/radio_seguridad_aviaria.kmz',
    layers: 'radio_seguridad_aviaria.kmz',
    categoria: 'RESTRICCION_TECNICA',
    opacidad: 0.75,
    visible: true,
    descripcion: 'Buffer normativo de 13 km alrededor de aeródromos y aeropuertos por riesgo aviario (RD 375-2013-MTC).',
    preset: ['preset_minam', 'preset_restriccion']
  },
  {
    id: 'granjas_zoosanitarias',
    nombre: 'Buffer Granjas Avícolas y Porcinas 5 a 10 km (SENASA / MINAM)',
    entidad: 'SENASA',
    urlWms: '/CAPAS/granjas_zoosanitarias.kmz',
    layers: 'granjas_zoosanitarias.kmz',
    categoria: 'RESTRICCION_TECNICA',
    opacidad: 0.75,
    visible: false,
    descripcion: 'Restricción técnico-sanitaria de 5 a 10 km de distanciamiento a granjas de producción pecuaria intensiva (D.S. 014-2017-MINAM).',
    preset: ['preset_minam', 'preset_restriccion']
  },
  {
    id: 'fallas_geologicas',
    nombre: 'Fallas Geológicas Activas ≥ 1 km (INGEMMET GEOCATMIN)',
    entidad: 'INGEMMET',
    urlWms: '/CAPAS/INGEMMET_Fallas_Geologicas_1000k.kmz',
    layers: 'INGEMMET_Fallas_Geologicas_1000k.kmz',
    categoria: 'RESTRICCION_TECNICA',
    opacidad: 0.85,
    visible: true,
    descripcion: 'Estructuras morfotectónicas activas con buffer de exclusión obligatoria de 1 km según D.L. 1278 (1.93 MB).',
    preset: ['preset_minam', 'preset_restriccion']
  },
  {
    id: 'zonas_criticas_pendientes',
    nombre: 'Pendientes del Terreno (< 25%) y Zonas Críticas (INGEMMET)',
    entidad: 'INGEMMET',
    urlWms: '/CAPAS/INGEMMET_Zonas_Criticas_Peligros.kmz',
    layers: 'INGEMMET_Zonas_Criticas_Peligros.kmz',
    categoria: 'RESTRICCION_TECNICA',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Zonas críticas por susceptibilidad a deslizamientos y laderas con pendiente > 25% descartadas por la Guía MINAM (350 KB).',
    preset: ['preset_minam', 'preset_restriccion']
  },
  {
    id: 'peligros_geologicos',
    nombre: 'Peligros Geológicos a Nivel Nacional (INGEMMET)',
    entidad: 'INGEMMET',
    urlWms: '/CAPAS/INGEMMET_Peligros_Geologicos_Nacional.kmz',
    layers: 'INGEMMET_Peligros_Geologicos_Nacional.kmz',
    categoria: 'RESTRICCION_TECNICA',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Cartografía de movimientos en masa e inundaciones de INGEMMET (390 KB).',
    preset: ['preset_restriccion']
  },
  {
    id: 'areas_degradadas',
    nombre: 'Inventario de Áreas Degradadas / Botaderos (OEFA / GEOEFA)',
    entidad: 'OEFA',
    urlWms: '/CAPAS/Inventario_Areas_Degradadas_OEFA.kmz',
    layers: 'Inventario_Areas_Degradadas_OEFA.kmz',
    categoria: 'RESTRICCION_TECNICA',
    opacidad: 0.85,
    visible: false,
    descripcion: 'Botaderos informales e inventario de áreas degradadas por residuos sólidos priorizados por OEFA para remediación y clausura.',
    preset: ['preset_oefa', 'preset_restriccion']
  },

  // =========================================================================
  // BLOQUE 3: INFRAESTRUCTURA Y PLANIFICACIÓN TERRITORIAL
  // =========================================================================

  // --- UNIFICACIÓN Y GESTIÓN JERÁRQUICA: RED VIAL Y ACCESIBILIDAD ---
  {
    id: 'red_vial_nacional',
    nombre: 'Red Vial Nacional (MTC Carreteras Troncales)',
    subNombre: '1. Red Vial Nacional / Carreteras Troncales (55 MB)',
    grupo: 'red_vial',
    groupNombre: 'Red Vial y Accesibilidad',
    entidad: 'MTC',
    urlWms: '/CAPAS/Red Vial Nacional.kmz',
    layers: 'Red Vial Nacional.kmz',
    categoria: 'INFRAESTRUCTURA_TERRITORIAL',
    opacidad: 0.85,
    visible: false,
    descripcion: 'Ejes longitudinales y transversales de la red vial nacional del MTC (55 MB).',
    preset: ['preset_vial']
  },
  {
    id: 'red_vial_departamental',
    nombre: 'Red Vial Departamental (MTC Rutas Regionales)',
    subNombre: '2. Red Vial Departamental / Regional (31 MB)',
    grupo: 'red_vial',
    groupNombre: 'Red Vial y Accesibilidad',
    entidad: 'MTC',
    urlWms: '/CAPAS/Red Vial Departamental.kmz',
    layers: 'Red Vial Departamental.kmz',
    categoria: 'INFRAESTRUCTURA_TERRITORIAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Red vial departamental articuladora interprovincial del MTC (31 MB).',
    preset: ['preset_vial']
  },
  {
    id: 'red_vial_vecinal',
    nombre: 'Red Vial Vecinal y Rural (MTC Caminos Vecinales)',
    subNombre: '3. Red Vial Vecinal / Caminos Rurales (116 MB)',
    grupo: 'red_vial',
    groupNombre: 'Red Vial y Accesibilidad',
    entidad: 'MTC',
    urlWms: '/CAPAS/Red Vial Vecinal.kmz',
    layers: 'Red Vial Vecinal.kmz',
    categoria: 'INFRAESTRUCTURA_TERRITORIAL',
    opacidad: 0.75,
    visible: false,
    descripcion: 'Caminos vecinales de conexión directa a predios rurales (116 MB).',
    preset: ['preset_vial']
  },
  {
    id: 'red_vial_trochas',
    nombre: 'Trochas Carrozables y Vías Conectoras (MTC / Rural)',
    subNombre: '4. Trochas Carrozables y Vías de Acceso',
    grupo: 'red_vial',
    groupNombre: 'Red Vial y Accesibilidad',
    entidad: 'MTC',
    urlWms: '/CAPAS/Trochas_Carrozables.kmz',
    layers: 'Trochas_Carrozables.kmz',
    categoria: 'INFRAESTRUCTURA_TERRITORIAL',
    opacidad: 0.75,
    visible: false,
    descripcion: 'Trochas carrozables y vías no afirmadas de acceso directo a terrenos.',
    preset: ['preset_vial']
  },

  // --- USO DE SUELO Y PLANIFICACIÓN ---
  {
    id: 'capacidad_uso_suelo',
    nombre: 'Capacidad de Uso Mayor del Suelo (CUM 10.6 MB - MINAM / MIDAGRI)',
    entidad: 'MINAM',
    urlWms: '/CAPAS/Capacidad de Uso mayo de Suelo.kmz',
    layers: 'Capacidad de Uso mayo de Suelo.kmz',
    categoria: 'INFRAESTRUCTURA_TERRITORIAL',
    opacidad: 0.8,
    visible: true,
    descripcion: 'Clasificación de tierras (D.S. 017-2009-AG): Cultivo en Limpio (A), Permanente (C), Pastos (P), Forestal (F) y Protección (X). Prohíbe IRS en suelos agrícolas A/C y prioriza Tierras de Protección X (10.6 MB).',
    preset: ['preset_minam']
  },
  {
    id: 'catastro_urbano',
    nombre: 'Manzanas Urbanas Formalizadas (Catastro Urbano COFOPRI)',
    subNombre: 'Manzanas Urbanas Formalizadas (COFOPRI)',
    entidad: 'COFOPRI',
    urlWms: '/CAPAS/Catastro Urbano.kmz',
    layers: 'Catastro Urbano.kmz',
    categoria: 'INFRAESTRUCTURA_TERRITORIAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Manzanas urbanas formalizadas, catastro urbano y zonas de expansión urbana GEOLLAQTA / COFOPRI (14.1 MB).',
    preset: ['preset_sbn', 'preset_minam']
  },
  {
    id: 'predios_estado_sinabip',
    nombre: 'Catastro Predial y Terrenos del Estado SINABIP (SBN)',
    subNombre: 'Catastro Predial SBN (SINABIP)',
    entidad: 'SBN',
    urlWms: '/CAPAS/predios_estado_sinabip.kmz',
    layers: 'predios_estado_sinabip.kmz',
    categoria: 'INFRAESTRUCTURA_TERRITORIAL',
    opacidad: 0.75,
    visible: false,
    descripcion: 'Catastro predial del Estado y propiedades inscritas en el SINABIP viables para afectación en uso o transferencia gratuita a la municipalidad (D.L. 1278).',
    preset: ['preset_sbn', 'preset_minam']
  },
  {
    id: 'catastro_minero',
    nombre: 'Catastro Minero Vigente (INGEMMET GEOCATMIN)',
    entidad: 'INGEMMET',
    urlWms: '/CAPAS/INGEMMET_Catastro_Minero_Vigente.kmz',
    layers: 'INGEMMET_Catastro_Minero_Vigente.kmz',
    categoria: 'INFRAESTRUCTURA_TERRITORIAL',
    opacidad: 0.75,
    visible: false,
    descripcion: 'Concesiones y derechos mineros titulados registrados en INGEMMET (448 KB).',
    preset: ['preset_sbn']
  },
  {
    id: 'cartas_geologicas_100k',
    nombre: 'Cartas Geológicas Nacionales 1:100k (INGEMMET)',
    entidad: 'INGEMMET',
    urlWms: '/CAPAS/INGEMMET_Cartas_Geologicas_501_100k.kmz',
    layers: 'INGEMMET_Cartas_Geologicas_501_100k.kmz',
    categoria: 'INFRAESTRUCTURA_TERRITORIAL',
    opacidad: 0.7,
    visible: false,
    descripcion: 'Cuadrángulos geológicos y litología regional del INGEMMET (307 KB).',
    preset: ['preset_sbn']
  },
  {
    id: 'infraestructura_disposicion',
    nombre: 'Infraestructuras de Disposición Final Existentes (GeoPerú / MINAM)',
    entidad: 'GEOPERU',
    urlWms: '/CAPAS/infraestructura_disposicion.kmz',
    layers: 'infraestructura_disposicion.kmz',
    categoria: 'INFRAESTRUCTURA_TERRITORIAL',
    opacidad: 0.9,
    visible: false,
    descripcion: 'Catastro oficial PCM / MINAM / GeoPerú (Capa 39441) de Rellenos Sanitarios autorizados.',
    preset: ['preset_minam', 'preset_oefa']
  },

  // =========================================================================
  // ZONIFICACIÓN ECOLÓGICA Y ECONÓMICA (ZEE) REGIONAL - SELECTOR DROPDOWN
  // =========================================================================
  {
    id: 'zee_cajamarca',
    nombre: 'ZEE Cajamarca (GORE Cajamarca / MINAM)',
    subNombre: 'Cajamarca (Aprobada MINAM)',
    departamento: 'Cajamarca',
    grupo: 'zee',
    groupNombre: 'Zonificación Ecológica y Económica por Regiones (ZEE)',
    entidad: 'GORE',
    urlWms: '/CAPAS/ZEE/CAJAMARCA/CAJAMARCA_ZEE.kmz',
    layers: 'CAJAMARCA_ZEE.kmz',
    categoria: 'ZEE_REGIONAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Zonificación Ecológica y Económica oficial de Cajamarca: Zonas de Protección, Productivas y Especiales.',
    preset: ['preset_zee', 'preset_minam']
  },
  {
    id: 'zee_amazonas',
    nombre: 'ZEE Amazonas (GORE Amazonas / MINAM)',
    subNombre: 'Amazonas',
    departamento: 'Amazonas',
    grupo: 'zee',
    groupNombre: 'Zonificación Ecológica y Económica por Regiones (ZEE)',
    entidad: 'GORE',
    urlWms: '/CAPAS/ZEE/AMAZONAS/AMAZONAS_ZEE.kmz',
    layers: 'AMAZONAS_ZEE.kmz',
    categoria: 'ZEE_REGIONAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Zonificación Ecológica y Económica del departamento de Amazonas (1,413 polígonos).',
    preset: ['preset_zee']
  },
  {
    id: 'zee_arequipa',
    nombre: 'ZEE Arequipa (GORE Arequipa / MINAM)',
    subNombre: 'Arequipa (Meso ZEE)',
    departamento: 'Arequipa',
    grupo: 'zee',
    groupNombre: 'Zonificación Ecológica y Económica por Regiones (ZEE)',
    entidad: 'GORE',
    urlWms: '/CAPAS/ZEE/AREQUIPA/AREQUIPA_ZEE.kmz',
    layers: 'AREQUIPA_ZEE.kmz',
    categoria: 'ZEE_REGIONAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Meso ZEE del departamento de Arequipa (Aprobada por Ordenanza Regional).',
    preset: ['preset_zee']
  },
  {
    id: 'zee_ayacucho',
    nombre: 'ZEE Ayacucho (GORE Ayacucho / MINAM)',
    subNombre: 'Ayacucho',
    departamento: 'Ayacucho',
    grupo: 'zee',
    groupNombre: 'Zonificación Ecológica y Económica por Regiones (ZEE)',
    entidad: 'GORE',
    urlWms: '/CAPAS/ZEE/AYACUCHO/AYACUCHO_ZEE.kmz',
    layers: 'AYACUCHO_ZEE.kmz',
    categoria: 'ZEE_REGIONAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Zonificación Ecológica y Económica aprobada del departamento de Ayacucho.',
    preset: ['preset_zee']
  },
  {
    id: 'zee_callao',
    nombre: 'ZEE Callao (Gobierno Regional Callao / MINAM)',
    subNombre: 'Callao',
    departamento: 'Callao',
    grupo: 'zee',
    groupNombre: 'Zonificación Ecológica y Económica por Regiones (ZEE)',
    entidad: 'GORE',
    urlWms: '/CAPAS/ZEE/CALLAO/CALLAO_ZEE.kmz',
    layers: 'CALLAO_ZEE.kmz',
    categoria: 'ZEE_REGIONAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Zonificación Ecológica y Económica de la Provincia Constitucional del Callao.',
    preset: ['preset_zee']
  },
  {
    id: 'zee_cusco',
    nombre: 'ZEE Cusco (GORE Cusco / MINAM)',
    subNombre: 'Cusco',
    departamento: 'Cusco',
    grupo: 'zee',
    groupNombre: 'Zonificación Ecológica y Económica por Regiones (ZEE)',
    entidad: 'GORE',
    urlWms: '/CAPAS/ZEE/CUSCO/CUSCO_ZEE.kmz',
    layers: 'CUSCO_ZEE.kmz',
    categoria: 'ZEE_REGIONAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Zonificación Ecológica y Económica aprobada del departamento del Cusco.',
    preset: ['preset_zee']
  },
  {
    id: 'zee_huancavelica',
    nombre: 'ZEE Huancavelica (GORE Huancavelica / MINAM)',
    subNombre: 'Huancavelica',
    departamento: 'Huancavelica',
    grupo: 'zee',
    groupNombre: 'Zonificación Ecológica y Económica por Regiones (ZEE)',
    entidad: 'GORE',
    urlWms: '/CAPAS/ZEE/HUANCAVELICA/HUANCAVELICA_ZEE.kmz',
    layers: 'HUANCAVELICA_ZEE.kmz',
    categoria: 'ZEE_REGIONAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Zonificación Ecológica y Económica oficial de Huancavelica.',
    preset: ['preset_zee']
  },
  {
    id: 'zee_huanuco',
    nombre: 'ZEE Huánuco (GORE Huánuco / MINAM)',
    subNombre: 'Huánuco',
    departamento: 'Huánuco',
    grupo: 'zee',
    groupNombre: 'Zonificación Ecológica y Económica por Regiones (ZEE)',
    entidad: 'GORE',
    urlWms: '/CAPAS/ZEE/HUANUCO/HUANUCO_ZEE.kmz',
    layers: 'HUANUCO_ZEE.kmz',
    categoria: 'ZEE_REGIONAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Zonificación Ecológica y Económica del departamento de Huánuco (Alta resolución).',
    preset: ['preset_zee']
  },
  {
    id: 'zee_junin',
    nombre: 'ZEE Junín (GORE Junín / MINAM)',
    subNombre: 'Junín',
    departamento: 'Junín',
    grupo: 'zee',
    groupNombre: 'Zonificación Ecológica y Económica por Regiones (ZEE)',
    entidad: 'GORE',
    urlWms: '/CAPAS/ZEE/JUNIN/JUNIN_ZEE.kmz',
    layers: 'JUNIN_ZEE.kmz',
    categoria: 'ZEE_REGIONAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Zonificación Ecológica y Económica aprobada del departamento de Junín.',
    preset: ['preset_zee']
  },
  {
    id: 'zee_lambayeque',
    nombre: 'ZEE Lambayeque (GORE Lambayeque / MINAM)',
    subNombre: 'Lambayeque',
    departamento: 'Lambayeque',
    grupo: 'zee',
    groupNombre: 'Zonificación Ecológica y Económica por Regiones (ZEE)',
    entidad: 'GORE',
    urlWms: '/CAPAS/ZEE/LAMBAYEQUE/LAMBAYEQUE_ZEE.kmz',
    layers: 'LAMBAYEQUE_ZEE.kmz',
    categoria: 'ZEE_REGIONAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Zonificación Ecológica y Económica del departamento de Lambayeque.',
    preset: ['preset_zee']
  },
  {
    id: 'zee_madre_de_dios',
    nombre: 'ZEE Madre de Dios (GORE Madre de Dios / MINAM)',
    subNombre: 'Madre de Dios',
    departamento: 'Madre de Dios',
    grupo: 'zee',
    groupNombre: 'Zonificación Ecológica y Económica por Regiones (ZEE)',
    entidad: 'GORE',
    urlWms: '/CAPAS/ZEE/MADRE_DE_DIOS/MADRE_DE_DIOS_ZEE.kmz',
    layers: 'MADRE_DE_DIOS_ZEE.kmz',
    categoria: 'ZEE_REGIONAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Zonificación Ecológica y Económica de la cuenca y territorio de Madre de Dios.',
    preset: ['preset_zee']
  },
  {
    id: 'zee_moquegua',
    nombre: 'ZEE Moquegua (GORE Moquegua / MINAM)',
    subNombre: 'Moquegua',
    departamento: 'Moquegua',
    grupo: 'zee',
    groupNombre: 'Zonificación Ecológica y Económica por Regiones (ZEE)',
    entidad: 'GORE',
    urlWms: '/CAPAS/ZEE/MOQUEGUA/MOQUEGUA_ZEE.kmz',
    layers: 'MOQUEGUA_ZEE.kmz',
    categoria: 'ZEE_REGIONAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Meso ZEE aprobada de Moquegua (2,659 unidades territoriales).',
    preset: ['preset_zee']
  },
  {
    id: 'zee_piura',
    nombre: 'ZEE Piura (GORE Piura / MINAM)',
    subNombre: 'Piura',
    departamento: 'Piura',
    grupo: 'zee',
    groupNombre: 'Zonificación Ecológica y Económica por Regiones (ZEE)',
    entidad: 'GORE',
    urlWms: '/CAPAS/ZEE/PIURA/PIURA_ZEE.kmz',
    layers: 'PIURA_ZEE.kmz',
    categoria: 'ZEE_REGIONAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Zonificación Ecológica y Económica del departamento de Piura.',
    preset: ['preset_zee']
  },
  {
    id: 'zee_puno',
    nombre: 'ZEE Puno (GORE Puno / MINAM)',
    subNombre: 'Puno',
    departamento: 'Puno',
    grupo: 'zee',
    groupNombre: 'Zonificación Ecológica y Económica por Regiones (ZEE)',
    entidad: 'GORE',
    urlWms: '/CAPAS/ZEE/PUNO/PUNO_ZEE.kmz',
    layers: 'PUNO_ZEE.kmz',
    categoria: 'ZEE_REGIONAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Zonificación Ecológica y Económica del altiplano y cuenca Titicaca en Puno.',
    preset: ['preset_zee']
  },
  {
    id: 'zee_san_martin',
    nombre: 'ZEE San Martín (GORE San Martín / MINAM)',
    subNombre: 'San Martín',
    departamento: 'San Martín',
    grupo: 'zee',
    groupNombre: 'Zonificación Ecológica y Económica por Regiones (ZEE)',
    entidad: 'GORE',
    urlWms: '/CAPAS/ZEE/SAN_MARTIN/SAN_MARTIN_ZEE.kmz',
    layers: 'SAN_MARTIN_ZEE.kmz',
    categoria: 'ZEE_REGIONAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Zonificación Ecológica y Económica pionera del departamento de San Martín.',
    preset: ['preset_zee']
  },
  {
    id: 'zee_tacna',
    nombre: 'ZEE Tacna (GORE Tacna / MINAM)',
    subNombre: 'Tacna',
    departamento: 'Tacna',
    grupo: 'zee',
    groupNombre: 'Zonificación Ecológica y Económica por Regiones (ZEE)',
    entidad: 'GORE',
    urlWms: '/CAPAS/ZEE/TACNA/TACNA_ZEE.kmz',
    layers: 'TACNA_ZEE.kmz',
    categoria: 'ZEE_REGIONAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Zonificación Ecológica y Económica del departamento fronterizo de Tacna.',
    preset: ['preset_zee']
  },
  {
    id: 'zee_tumbes',
    nombre: 'ZEE Tumbes (GORE Tumbes / MINAM)',
    subNombre: 'Tumbes',
    departamento: 'Tumbes',
    grupo: 'zee',
    groupNombre: 'Zonificación Ecológica y Económica por Regiones (ZEE)',
    entidad: 'GORE',
    urlWms: '/CAPAS/ZEE/TUMBES/TUMBES_ZEE.kmz',
    layers: 'TUMBES_ZEE.kmz',
    categoria: 'ZEE_REGIONAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Zonificación Ecológica y Económica de Tumbes (Ecosistemas de manglares y costa norte).',
    preset: ['preset_zee']
  },
  {
    id: 'zee_ucayali',
    nombre: 'ZEE Ucayali (GORE Ucayali / MINAM)',
    subNombre: 'Ucayali',
    departamento: 'Ucayali',
    grupo: 'zee',
    groupNombre: 'Zonificación Ecológica y Económica por Regiones (ZEE)',
    entidad: 'GORE',
    urlWms: '/CAPAS/ZEE/UCAYALI/UCAYALI_ZEE.kmz',
    layers: 'UCAYALI_ZEE.kmz',
    categoria: 'ZEE_REGIONAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Zonificación Ecológica y Económica de la cuenca amazónica en Ucayali.',
    preset: ['preset_zee']
  },
  {
    id: 'zee_loreto_alto_amazonas',
    nombre: 'ZEE Loreto - Alto Amazonas (GORE Loreto / MINAM)',
    subNombre: 'Loreto (Alto Amazonas)',
    departamento: 'Loreto (Alto Amazonas)',
    grupo: 'zee',
    groupNombre: 'Zonificación Ecológica y Económica por Regiones (ZEE)',
    entidad: 'GORE',
    urlWms: '/CAPAS/ZEE/LORETO_ALTO_AMAZONAS/LORETO_ALTO_AMAZONAS_ZEE.kmz',
    layers: 'LORETO_ALTO_AMAZONAS_ZEE.kmz',
    categoria: 'ZEE_REGIONAL',
    opacidad: 0.8,
    visible: false,
    descripcion: 'Zonificación Ecológica y Económica de la provincia de Alto Amazonas en Loreto.',
    preset: ['preset_zee']
  }
];

export const LAYER_PRESETS: LayerPreset[] = [
  {
    id: 'preset_minam',
    nombre: 'Estándar D.L. 1278 (MINAM Oficial)',
    descripcion: 'Filtro automático con exclusiones absolutas, restricciones sanitarias y capacidad de uso de suelo.',
    layerIds: [
      'anp_definitivas', 'catastro_monumentos', 'rios_lagos_ana',
      'fallas_geologicas', 'radio_seguridad_aviaria', 'capacidad_uso_suelo'
    ]
  },
  {
    id: 'preset_exclusion',
    nombre: 'Bloque 1: Exclusión Legal y Ambiental (R1/R2)',
    descripcion: 'Solo capas de prohibición absoluta: ANP SERNANP, Patrimonio CIRA MINCUL y Fajas ANA.',
    layerIds: [
      'anp_definitivas', 'catastro_monumentos', 'rios_lagos_ana', 'lagos_lagunas'
    ]
  },
  {
    id: 'preset_restriccion',
    nombre: 'Bloque 2: Restricciones Técnicas (Modelo R3)',
    descripcion: 'Distancias a poblados (≥500m), aeropuertos (≥13km), granjas (5-10km), fallas y pendientes.',
    layerIds: [
      'catastro_urbano_buffer', 'radio_seguridad_aviaria', 'granjas_zoosanitarias',
      'fallas_geologicas', 'zonas_criticas_pendientes', 'areas_degradadas'
    ]
  },
  {
    id: 'preset_vial',
    nombre: 'Bloque 3: Red Vial y Accesibilidad Logística (MTC)',
    descripcion: 'Redes viales nacionales, departamentales, vecinales y trochas carrozables.',
    layerIds: ['red_vial_nacional', 'red_vial_departamental', 'red_vial_vecinal', 'red_vial_trochas']
  },
  {
    id: 'preset_zee',
    nombre: 'Zonificación Ecológica y Económica (ZEE MINAM)',
    descripcion: 'Meso y Macro ZEE para compatibilidad de uso ecológico-económico.',
    layerIds: ['zee_cajamarca', 'capacidad_uso_suelo', 'anp_definitivas']
  },
  {
    id: 'preset_sbn',
    nombre: 'Planificación Territorial y Catastro Predial (SBN)',
    descripcion: 'Evaluación de predios del Estado SINABIP vs concesiones mineras y catastro.',
    layerIds: ['predios_estado_sinabip', 'catastro_urbano', 'catastro_minero', 'capacidad_uso_suelo']
  }
];
